"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, ArrowRight, Check, Loader2 } from "lucide-react";
import { categories, painPoints, projectTypes } from "@/lib/options";

type Kind="designer"|"supplier";
type FormData=Record<string,string|string[]|boolean>;
const field="w-full border border-black/15 bg-white px-4 py-3.5 outline-none transition focus:border-black";

function Choice({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} className={`min-h-12 border px-4 py-3 text-left text-sm transition ${active?"border-black bg-black text-white":"border-black/12 bg-white hover:border-black/35"}`}>{label}</button>}
function Multi({title,options,value,onChange,limit}:{title:string;options:string[];value:string[];onChange:(v:string[])=>void;limit?:number}){return <div><div className="mb-3 flex items-end justify-between"><h3 className="font-bold">{title}</h3>{limit&&<span className="text-xs text-black/40">最多选择{limit}项</span>}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{options.map(o=><Choice key={o} label={o} active={value.includes(o)} onClick={()=>{if(value.includes(o))onChange(value.filter(x=>x!==o));else if(!limit||value.length<limit)onChange([...value,o])}} />)}</div></div>}

export default function ResourceForm({kind}:{kind:Kind}){
 const supplier=kind==="supplier"; const total=5; const [step,setStep]=useState(1); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const [data,setData]=useState<FormData>({project_types:[],categories:[],priority_categories:[],pain_points:[],support_types:[],privacy_agreed:false});
 const set=(k:string,v:string|string[]|boolean)=>setData(d=>({...d,[k]:v})); const selected=data.categories as string[];
 const title=useMemo(()=>supplier?"品牌或供应商资源登记":"设计师或设计机构资源登记",[supplier]);
 async function submit(){setBusy(true);setError("");try{const res=await fetch(`/api/submissions/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const body=await res.json() as {error?:string};if(!res.ok)throw new Error(body.error||"提交失败");location.href=`/success?type=${kind}`;}catch(e){setError(e instanceof Error?e.message:"提交失败，请稍后重试");setBusy(false)}}
 return <main className="min-h-screen bg-[#f7f7f5]"><div className="mx-auto max-w-3xl px-5 py-6 sm:px-8 sm:py-10">
  <header className="mb-8"><div className="flex items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 text-sm text-black/50"><ArrowLeft size={16}/>返回</Link><Image src="/roundtable-logo.png" alt="设计青年圆桌派" width={1750} height={512} unoptimized className="h-auto w-[180px] object-contain" /></div><div className="mt-7 flex items-end justify-between"><div><p className="text-xs font-bold text-[#9a7a00]">RESOURCE PROFILE</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">{title}</h1></div><span className="text-sm font-bold">{step} / {total}</span></div><div className="mt-5 h-1 bg-black/10"><div className="h-full bg-[#ffd400] transition-all" style={{width:`${step/total*100}%`}}/></div></header>
  <section className="border border-black/10 bg-white p-5 shadow-[0_12px_40px_rgba(0,0,0,.04)] sm:p-8">
   {step===1&&<div className="space-y-5"><h2 className="text-xl font-bold">先认识一下</h2><label className="block text-sm font-bold">公司或机构名称<input className={`${field} mt-2`} value={String(data.company_name||"")} onChange={e=>set("company_name",e.target.value)} /></label>{supplier&&<label className="block text-sm font-bold">品牌名称<input className={`${field} mt-2`} value={String(data.brand_name||"")} onChange={e=>set("brand_name",e.target.value)} /></label>}<div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold">填表人<input className={`${field} mt-2`} value={String(data.contact_name||"")} onChange={e=>set("contact_name",e.target.value)} /></label><label className="block text-sm font-bold">职位<input className={`${field} mt-2`} value={String(data.position||"")} onChange={e=>set("position",e.target.value)} /></label><label className="block text-sm font-bold">手机号<input type="tel" className={`${field} mt-2`} value={String(data.phone||"")} onChange={e=>set("phone",e.target.value)} /></label><label className="block text-sm font-bold">微信号<input className={`${field} mt-2`} value={String(data.wechat||"")} onChange={e=>set("wechat",e.target.value)} /></label><label className="block text-sm font-bold">所在省份<input className={`${field} mt-2`} value={String(data.province||"")} onChange={e=>set("province",e.target.value)} /></label><label className="block text-sm font-bold">所在城市<input className={`${field} mt-2`} value={String(data.city||"")} onChange={e=>set("city",e.target.value)} /></label></div></div>}
   {step===2&&!supplier&&<div className="space-y-7"><h2 className="text-xl font-bold">项目情况</h2><Multi title="主要项目类型" options={projectTypes} value={data.project_types as string[]} onChange={v=>set("project_types",v)}/><label className="block text-sm font-bold">年项目量<select className={`${field} mt-2`} value={String(data.annual_project_count||"")} onChange={e=>set("annual_project_count",e.target.value)}><option value="">请选择</option>{["1至5个","6至10个","11至20个","21至50个","50个以上"].map(x=><option key={x}>{x}</option>)}</select></label></div>}
   {step===2&&supplier&&<div className="space-y-6"><h2 className="text-xl font-bold">企业身份与责任</h2><label className="block text-sm font-bold">企业身份<select className={`${field} mt-2`} value={String(data.supplier_type||"")} onChange={e=>set("supplier_type",e.target.value)}><option value="">请选择</option>{["厂家","品牌方","总代理","区域代理","经销商","施工或安装服务商","综合服务商","其他"].map(x=><option key={x}>{x}</option>)}</select></label>{["授权或代理区域","实际签约收款主体","实际供货或交付主体","售后责任主体"].map((x,i)=><label key={x} className="block text-sm font-bold">{x}<input className={`${field} mt-2`} value={String(data[["authorized_regions","contract_entity","delivery_entity","after_sales_entity"][i]]||"")} onChange={e=>set(["authorized_regions","contract_entity","delivery_entity","after_sales_entity"][i],e.target.value)}/></label>)}</div>}
   {step===3&&!supplier&&<div className="space-y-7"><h2 className="text-xl font-bold">目前最想解决的问题</h2><Multi title="请选择最关注的问题" options={painPoints} value={data.pain_points as string[]} onChange={v=>set("pain_points",v)} limit={5}/></div>}
   {step===3&&supplier&&<div className="space-y-7"><h2 className="text-xl font-bold">主营能力</h2><Multi title="主营品类" options={categories} value={selected} onChange={v=>set("categories",v)} limit={3}/><Multi title="可以提供的支持" options={["样品","选品","报价","深化","技术支持","项目配合","售后","媒体或宣发","游学或活动"]} value={data.support_types as string[]} onChange={v=>set("support_types",v)}/></div>}
   {step===4&&!supplier&&<div className="space-y-7"><h2 className="text-xl font-bold">材料合作概况</h2><label className="block text-sm font-bold">年度物料金额，选填<select className={`${field} mt-2`} value={String(data.annual_material_amount||"")} onChange={e=>set("annual_material_amount",e.target.value)}><option value="">请选择</option>{["50万元以下","50至100万元","100至300万元","300至500万元","500至1000万元","1000至3000万元","3000万元以上","不方便透露"].map(x=><option key={x}>{x}</option>)}</select></label><Multi title="所有涉及品类" options={categories} value={selected} onChange={v=>set("categories",v)}/></div>}
   {step===4&&supplier&&<div className="space-y-5"><h2 className="text-xl font-bold">项目与服务</h2><Multi title="主要项目类型" options={projectTypes} value={data.project_types as string[]} onChange={v=>set("project_types",v)}/><label className="block text-sm font-bold">代表项目<textarea className={`${field} mt-2 min-h-28 resize-y`} value={String(data.representative_projects||"")} onChange={e=>set("representative_projects",e.target.value)}/></label></div>}
   {step===5&&<div className="space-y-6"><h2 className="text-xl font-bold">最后确认</h2>{!supplier&&selected.length>0&&<Multi title="重点合作品类" options={selected} value={data.priority_categories as string[]} onChange={v=>set("priority_categories",v)} limit={3}/>}<label className="block text-sm font-bold">{supplier?"对圆桌派合作有什么期待？":"最希望平台提供哪些支持？"}<textarea className={`${field} mt-2 min-h-32 resize-y`} value={String(data.expectation||"")} onChange={e=>set("expectation",e.target.value)}/></label><label className="flex cursor-pointer items-start gap-3 border border-black/10 bg-[#f7f7f5] p-4"><input type="checkbox" className="mt-1 h-5 w-5 accent-black" checked={Boolean(data.privacy_agreed)} onChange={e=>set("privacy_agreed",e.target.checked)}/><span className="text-sm leading-6">我已阅读并同意<Link href="/privacy" target="_blank" className="font-bold underline">《信息收集与使用说明》</Link></span></label>{error&&<p className="text-sm font-bold text-red-600">{error}</p>}</div>}
  </section>
  <div className="sticky bottom-0 mt-5 flex gap-3 bg-[#f7f7f5]/95 py-4 backdrop-blur"><button type="button" disabled={step===1} onClick={()=>setStep(s=>s-1)} className="min-h-12 flex-1 border border-black/15 bg-white px-5 font-bold disabled:opacity-30">上一步</button>{step<total?<button type="button" onClick={()=>setStep(s=>s+1)} className="flex min-h-12 flex-[1.6] items-center justify-center gap-2 bg-black px-5 font-bold text-white">下一步<ArrowRight size={18}/></button>:<button type="button" disabled={busy||!data.privacy_agreed} onClick={submit} className="flex min-h-12 flex-[1.6] items-center justify-center gap-2 bg-[#ffd400] px-5 font-bold disabled:opacity-40">{busy?<Loader2 className="animate-spin" size={18}/>:<Check size={18}/>}提交资料</button>}</div>
 </div></main>
}




